#!/usr/bin/env bash
# UIComponent 의 각 *.xcassets 를 스캔해 카탈로그별 public 접근자를 생성한다.
#   Colors.xcassets -> Sources/Colors+.swift   (colorset -> Color)
#   Assets.xcassets -> Sources/Assets+.swift   (imageset -> Image)
# 빌드 시 Xcode 런스크립트("asset generate" 페이즈)가 자동 실행. 수동 실행: ./scripts/gen-assets.sh
# 결과물(Sources/UIComponent/Sources/*+.swift)은 커밋한다 — 손으로 편집 금지.
#
# ponytail: 카탈로그별로 colorset/imageset 둘 다 스캔해 "있는 것만" 방출(타입은 카탈로그가 강제하는 게 아님).
#           네임스페이스 폴더(provides-namespace) 처리. 예약어(`default` 등)·이름 충돌은
#           Swift 컴파일 에러로 드러난다(조용히 안 깨짐) — 그때 이름만 바꾸면 됨.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PKG="$(dirname "$SCRIPT_DIR")"
RES="$PKG/Sources/UIComponent/Resources"
OUT_DIR="$PKG/Sources/UIComponent/Sources"

if [ ! -d "$RES" ]; then
  echo "error: resources dir not found at $RES" >&2
  exit 1
fi
mkdir -p "$OUT_DIR"

# 변경 감지: 카탈로그 입력의 해시가 직전 실행과 같으면 생성 스킵.
# 빌드 페이즈에서 매번 호출돼도 자산이 안 바뀌었으면 즉시 종료 → 불필요한 재컴파일/working-tree churn 방지.
# `--force` 로 무시. 해시 파일은 머신별 산출물이라 커밋하지 않는다(.gitignore).
HASH_FILE="$SCRIPT_DIR/.assets.hash"
# 경로(이름)만 해싱 — 파일 내용은 안 읽는다. set 추가/삭제/이름변경 감지.
# ponytail: provides-namespace 토글(폴더명 그대로 두고 켜고/끄기)은 경로가 안 바뀌어 못 잡음.
#           평평한 카탈로그라 미사용 — 쓰게 되면 토글 후 `--force` 1회, 또는 Contents.json 내용 해싱으로 교체.
NEW_HASH="$(find "$RES"/*.xcassets | LC_ALL=C sort | shasum | cut -d' ' -f1)"
if [ "${1:-}" != "--force" ] && [ -f "$HASH_FILE" ] && [ "$NEW_HASH" = "$(cat "$HASH_FILE")" ]; then
  echo "assets unchanged — skip codegen"
  exit 0
fi

# asset 의 런타임 이름(네임스페이스 포함). $1=asset 경로, $2=카탈로그 루트. 예: "Brand/Primary"
runtime_name() {
  base="$(basename "$1")"; name="${base%.*}"
  dir="$(dirname "$1")"; prefix=""
  while [ "$dir" != "$2" ] && [ "$dir" != "/" ]; do
    folder="$(basename "$dir")"
    if grep -Eq '"provides-namespace"[[:space:]]*:[[:space:]]*true' "$dir/Contents.json" 2>/dev/null; then
      prefix="$folder/$prefix"
    fi
    dir="$(dirname "$dir")"
  done
  printf '%s%s' "$prefix" "$name"
}

# 런타임 이름 -> swift 식별자. "Brand/Primary-Dark" -> "brandPrimaryDark"
ident() {
  awk '{
    n = split($0, p, /[^A-Za-z0-9]+/); out = ""
    for (i = 1; i <= n; i++) {
      if (p[i] == "") continue
      seg = (out == "") ? tolower(substr(p[i],1,1)) substr(p[i],2) \
                        : toupper(substr(p[i],1,1)) substr(p[i],2)
      out = out seg
    }
    if (out ~ /^[0-9]/) out = "_" out
    print out
  }' <<<"$1"
}

# $1=카탈로그 경로, $2=set 확장자(colorset/imageset), $3=swift 타입(Color/Image)
emit() {
  find "$1" -type d -name "*.$2" | sort | while read -r asset; do
    rn="$(runtime_name "$asset" "$1")"
    printf '    static let %s = %s("%s", bundle: .module)\n' "$(ident "$rn")" "$3" "$rn"
  done
}

shopt -s nullglob
for catalog in "$RES"/*.xcassets; do
  base="$(basename "$catalog" .xcassets)"
  out="$OUT_DIR/${base}+.swift"
  colors="$(emit "$catalog" colorset Color)"
  images="$(emit "$catalog" imageset Image)"
  {
    echo "// Generated by scripts/gen-assets.sh from ${base}.xcassets — DO NOT EDIT."
    echo "import SwiftUI"
    if [ -n "$colors" ]; then echo; echo "public extension Color {"; echo "$colors"; echo "}"; fi
    if [ -n "$images" ]; then echo; echo "public extension Image {"; echo "$images"; echo "}"; fi
    if [ -z "$colors" ] && [ -z "$images" ]; then
      echo; echo "// (이 카탈로그에 colorset/imageset 없음 — 자산 추가 후 재빌드)"
    fi
  } >"$out"
  echo "wrote $out"
done

printf '%s' "$NEW_HASH" >"$HASH_FILE"
