#!/usr/bin/env bash
# UIComponent 의 각 *.xcassets 를 스캔해 카탈로그별 public 접근자를 생성한다.
#   Colors.xcassets -> Resources/Colors+.swift   (colorset -> Color)
#   Assets.xcassets -> Resources/Assets+.swift   (imageset -> Image)
# 자산 추가/이름변경/삭제 후 실행:  make assets   (또는 ./scripts/gen-assets.sh)
# 결과물(Resources/*+.swift)은 커밋한다 — 손으로 편집 금지.
#
# ponytail: 카탈로그별로 colorset/imageset 둘 다 스캔해 "있는 것만" 방출(타입은 카탈로그가 강제하는 게 아님).
#           네임스페이스 폴더(provides-namespace) 처리. 예약어(`default` 등)·이름 충돌은
#           Swift 컴파일 에러로 드러난다(조용히 안 깨짐) — 그때 이름만 바꾸면 됨.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PKG="$(dirname "$SCRIPT_DIR")"
RES="$PKG/Sources/UIComponent/Resources"

if [ ! -d "$RES" ]; then
  echo "error: resources dir not found at $RES" >&2
  exit 1
fi

# asset 의 런타임 이름(네임스페이스 포함). $1=asset 경로, $2=카탈로그 루트. 예: "Brand/Primary"
runtime_name() {
  base="$(basename "$1")"; name="${base%.*}"
  dir="$(dirname "$1")"; prefix=""
  while [ "$dir" != "$2" ] && [ "$dir" != "/" ]; do
    folder="$(basename "$dir")"
    if grep -Eq '"provides-namespace"[[:space:]]*:[[:space:]]*true' "$dir/Contents.json" 2>/dev/null; then
      prefix="$folder/$prefix"
    fi
    dir="$(dirname "$dir")"
  done
  printf '%s%s' "$prefix" "$name"
}

# 런타임 이름 -> swift 식별자. "Brand/Primary-Dark" -> "brandPrimaryDark"
ident() {
  awk '{
    n = split($0, p, /[^A-Za-z0-9]+/); out = ""
    for (i = 1; i <= n; i++) {
      if (p[i] == "") continue
      seg = (out == "") ? tolower(substr(p[i],1,1)) substr(p[i],2) \
                        : toupper(substr(p[i],1,1)) substr(p[i],2)
      out = out seg
    }
    if (out ~ /^[0-9]/) out = "_" out
    print out
  }' <<<"$1"
}

# $1=카탈로그 경로, $2=set 확장자(colorset/imageset), $3=swift 타입(Color/Image)
emit() {
  find "$1" -type d -name "*.$2" | sort | while read -r asset; do
    rn="$(runtime_name "$asset" "$1")"
    printf '    static let %s = %s("%s", bundle: .module)\n' "$(ident "$rn")" "$3" "$rn"
  done
}

shopt -s nullglob
for catalog in "$RES"/*.xcassets; do
  base="$(basename "$catalog" .xcassets)"
  out="$RES/${base}+.swift"
  colors="$(emit "$catalog" colorset Color)"
  images="$(emit "$catalog" imageset Image)"
  {
    echo "// Generated by scripts/gen-assets.sh from ${base}.xcassets — DO NOT EDIT."
    echo "import SwiftUI"
    if [ -n "$colors" ]; then echo; echo "public extension Color {"; echo "$colors"; echo "}"; fi
    if [ -n "$images" ]; then echo; echo "public extension Image {"; echo "$images"; echo "}"; fi
    if [ -z "$colors" ] && [ -z "$images" ]; then
      echo; echo "// (이 카탈로그에 colorset/imageset 없음 — 자산 추가 후 make assets)"
    fi
  } >"$out"
  echo "wrote $out"
done
