// Generated by scripts/gen-assets.sh from Colors.xcassets — DO NOT EDIT.
import SwiftUI
import UIKit

public extension Color {
    static let accentColor = Color("AccentColor", bundle: .module)
    static let blackFixed = Color("blackFixed", bundle: .module)
    static let cherry = Color("cherry", bundle: .module)
    static let cherry100 = Color("cherry100", bundle: .module)
    static let cherry200 = Color("cherry200", bundle: .module)
    static let cherry300 = Color("cherry300", bundle: .module)
    static let cherry400 = Color("cherry400", bundle: .module)
    static let cherry50 = Color("cherry50", bundle: .module)
    static let cherry500 = Color("cherry500", bundle: .module)
    static let cherry700 = Color("cherry700", bundle: .module)
    static let danger = Color("danger", bundle: .module)
    static let gray100 = Color("gray100", bundle: .module)
    static let gray200 = Color("gray200", bundle: .module)
    static let gray300 = Color("gray300", bundle: .module)
    static let gray400 = Color("gray400", bundle: .module)
    static let gray50 = Color("gray50", bundle: .module)
    static let gray500 = Color("gray500", bundle: .module)
    static let gray600 = Color("gray600", bundle: .module)
    static let gray700 = Color("gray700", bundle: .module)
    static let gray800 = Color("gray800", bundle: .module)
    static let gray850 = Color("gray850", bundle: .module)
    static let gray900 = Color("gray900", bundle: .module)
    static let gray950 = Color("gray950", bundle: .module)
    static let info = Color("info", bundle: .module)
    static let melon = Color("melon", bundle: .module)
    static let pudding = Color("pudding", bundle: .module)
    static let success = Color("success", bundle: .module)
    static let warning = Color("warning", bundle: .module)
    static let whiteFixed = Color("whiteFixed", bundle: .module)
}

public extension ShapeStyle where Self == Color {
    static var accentColor: Color { .accentColor }
    static var blackFixed: Color { .blackFixed }
    static var cherry: Color { .cherry }
    static var cherry100: Color { .cherry100 }
    static var cherry200: Color { .cherry200 }
    static var cherry300: Color { .cherry300 }
    static var cherry400: Color { .cherry400 }
    static var cherry50: Color { .cherry50 }
    static var cherry500: Color { .cherry500 }
    static var cherry700: Color { .cherry700 }
    static var danger: Color { .danger }
    static var gray100: Color { .gray100 }
    static var gray200: Color { .gray200 }
    static var gray300: Color { .gray300 }
    static var gray400: Color { .gray400 }
    static var gray50: Color { .gray50 }
    static var gray500: Color { .gray500 }
    static var gray600: Color { .gray600 }
    static var gray700: Color { .gray700 }
    static var gray800: Color { .gray800 }
    static var gray850: Color { .gray850 }
    static var gray900: Color { .gray900 }
    static var gray950: Color { .gray950 }
    static var info: Color { .info }
    static var melon: Color { .melon }
    static var pudding: Color { .pudding }
    static var success: Color { .success }
    static var warning: Color { .warning }
    static var whiteFixed: Color { .whiteFixed }
}

public extension UIColor {
    static var accentColor: UIColor { UIColor(resource: ColorResource(name: "AccentColor", bundle: .module)) }
    static var blackFixed: UIColor { UIColor(resource: ColorResource(name: "blackFixed", bundle: .module)) }
    static var cherry: UIColor { UIColor(resource: ColorResource(name: "cherry", bundle: .module)) }
    static var cherry100: UIColor { UIColor(resource: ColorResource(name: "cherry100", bundle: .module)) }
    static var cherry200: UIColor { UIColor(resource: ColorResource(name: "cherry200", bundle: .module)) }
    static var cherry300: UIColor { UIColor(resource: ColorResource(name: "cherry300", bundle: .module)) }
    static var cherry400: UIColor { UIColor(resource: ColorResource(name: "cherry400", bundle: .module)) }
    static var cherry50: UIColor { UIColor(resource: ColorResource(name: "cherry50", bundle: .module)) }
    static var cherry500: UIColor { UIColor(resource: ColorResource(name: "cherry500", bundle: .module)) }
    static var cherry700: UIColor { UIColor(resource: ColorResource(name: "cherry700", bundle: .module)) }
    static var danger: UIColor { UIColor(resource: ColorResource(name: "danger", bundle: .module)) }
    static var gray100: UIColor { UIColor(resource: ColorResource(name: "gray100", bundle: .module)) }
    static var gray200: UIColor { UIColor(resource: ColorResource(name: "gray200", bundle: .module)) }
    static var gray300: UIColor { UIColor(resource: ColorResource(name: "gray300", bundle: .module)) }
    static var gray400: UIColor { UIColor(resource: ColorResource(name: "gray400", bundle: .module)) }
    static var gray50: UIColor { UIColor(resource: ColorResource(name: "gray50", bundle: .module)) }
    static var gray500: UIColor { UIColor(resource: ColorResource(name: "gray500", bundle: .module)) }
    static var gray600: UIColor { UIColor(resource: ColorResource(name: "gray600", bundle: .module)) }
    static var gray700: UIColor { UIColor(resource: ColorResource(name: "gray700", bundle: .module)) }
    static var gray800: UIColor { UIColor(resource: ColorResource(name: "gray800", bundle: .module)) }
    static var gray850: UIColor { UIColor(resource: ColorResource(name: "gray850", bundle: .module)) }
    static var gray900: UIColor { UIColor(resource: ColorResource(name: "gray900", bundle: .module)) }
    static var gray950: UIColor { UIColor(resource: ColorResource(name: "gray950", bundle: .module)) }
    static var info: UIColor { UIColor(resource: ColorResource(name: "info", bundle: .module)) }
    static var melon: UIColor { UIColor(resource: ColorResource(name: "melon", bundle: .module)) }
    static var pudding: UIColor { UIColor(resource: ColorResource(name: "pudding", bundle: .module)) }
    static var success: UIColor { UIColor(resource: ColorResource(name: "success", bundle: .module)) }
    static var warning: UIColor { UIColor(resource: ColorResource(name: "warning", bundle: .module)) }
    static var whiteFixed: UIColor { UIColor(resource: ColorResource(name: "whiteFixed", bundle: .module)) }
}
