// Generated by scripts/gen-assets.sh from Assets.xcassets — DO NOT EDIT.
import SwiftUI
import UIKit

public extension Image {
    static let icSocialApple = Image("IC_Social_Apple", bundle: .module)
}

public extension UIImage {
    static var icSocialApple: UIImage { UIImage(resource: ImageResource(name: "IC_Social_Apple", bundle: .module)) }
}
