// Generated by scripts/gen-assets.sh from Assets.xcassets — DO NOT EDIT.
import SwiftUI
import UIKit

public extension Image {
    static let icCloseRound = Image("Ic_Close_Round", bundle: .module)
}

public extension UIImage {
    static var icCloseRound: UIImage { UIImage(resource: ImageResource(name: "Ic_Close_Round", bundle: .module)) }
}
