// Generated by scripts/gen-assets.sh from Colors.xcassets — DO NOT EDIT.
import SwiftUI
import UIKit

public extension Color {
    static let accentColor = Color("AccentColor", bundle: .module)
    static let black25 = Color("black25", bundle: .module)
    static let black5 = Color("black5", bundle: .module)
    static let black50 = Color("black50", bundle: .module)
    static let black75 = Color("black75", bundle: .module)
    static let blackFixed = Color("blackFixed", bundle: .module)
    static let cherry = Color("cherry", bundle: .module)
    static let cherry100 = Color("cherry100", bundle: .module)
    static let cherry200 = Color("cherry200", bundle: .module)
    static let cherry300 = Color("cherry300", bundle: .module)
    static let cherry400 = Color("cherry400", bundle: .module)
    static let cherry50 = Color("cherry50", bundle: .module)
    static let cherry500 = Color("cherry500", bundle: .module)
    static let cherry600 = Color("cherry600", bundle: .module)
    static let cherry700 = Color("cherry700", bundle: .module)
    static let gray100 = Color("gray100", bundle: .module)
    static let gray200 = Color("gray200", bundle: .module)
    static let gray300 = Color("gray300", bundle: .module)
    static let gray400 = Color("gray400", bundle: .module)
    static let gray50 = Color("gray50", bundle: .module)
    static let gray500 = Color("gray500", bundle: .module)
    static let gray600 = Color("gray600", bundle: .module)
    static let gray700 = Color("gray700", bundle: .module)
    static let gray800 = Color("gray800", bundle: .module)
    static let gray850 = Color("gray850", bundle: .module)
    static let gray900 = Color("gray900", bundle: .module)
    static let gray950 = Color("gray950", bundle: .module)
    static let melon500 = Color("melon500", bundle: .module)
    static let melon600 = Color("melon600", bundle: .module)
    static let pudding500 = Color("pudding500", bundle: .module)
    static let pudding600 = Color("pudding600", bundle: .module)
    static let soda500 = Color("soda500", bundle: .module)
    static let white25 = Color("white25", bundle: .module)
    static let white50 = Color("white50", bundle: .module)
    static let white75 = Color("white75", bundle: .module)
    static let whiteFixed = Color("whiteFixed", bundle: .module)
}

public extension ShapeStyle where Self == Color {
    static var accentColor: Color { .accentColor }
    static var black25: Color { .black25 }
    static var black5: Color { .black5 }
    static var black50: Color { .black50 }
    static var black75: Color { .black75 }
    static var blackFixed: Color { .blackFixed }
    static var cherry: Color { .cherry }
    static var cherry100: Color { .cherry100 }
    static var cherry200: Color { .cherry200 }
    static var cherry300: Color { .cherry300 }
    static var cherry400: Color { .cherry400 }
    static var cherry50: Color { .cherry50 }
    static var cherry500: Color { .cherry500 }
    static var cherry600: Color { .cherry600 }
    static var cherry700: Color { .cherry700 }
    static var gray100: Color { .gray100 }
    static var gray200: Color { .gray200 }
    static var gray300: Color { .gray300 }
    static var gray400: Color { .gray400 }
    static var gray50: Color { .gray50 }
    static var gray500: Color { .gray500 }
    static var gray600: Color { .gray600 }
    static var gray700: Color { .gray700 }
    static var gray800: Color { .gray800 }
    static var gray850: Color { .gray850 }
    static var gray900: Color { .gray900 }
    static var gray950: Color { .gray950 }
    static var melon500: Color { .melon500 }
    static var melon600: Color { .melon600 }
    static var pudding500: Color { .pudding500 }
    static var pudding600: Color { .pudding600 }
    static var soda500: Color { .soda500 }
    static var white25: Color { .white25 }
    static var white50: Color { .white50 }
    static var white75: Color { .white75 }
    static var whiteFixed: Color { .whiteFixed }
}

public extension UIColor {
    static var accentColor: UIColor { UIColor(resource: ColorResource(name: "AccentColor", bundle: .module)) }
    static var black25: UIColor { UIColor(resource: ColorResource(name: "black25", bundle: .module)) }
    static var black5: UIColor { UIColor(resource: ColorResource(name: "black5", bundle: .module)) }
    static var black50: UIColor { UIColor(resource: ColorResource(name: "black50", bundle: .module)) }
    static var black75: UIColor { UIColor(resource: ColorResource(name: "black75", bundle: .module)) }
    static var blackFixed: UIColor { UIColor(resource: ColorResource(name: "blackFixed", bundle: .module)) }
    static var cherry: UIColor { UIColor(resource: ColorResource(name: "cherry", bundle: .module)) }
    static var cherry100: UIColor { UIColor(resource: ColorResource(name: "cherry100", bundle: .module)) }
    static var cherry200: UIColor { UIColor(resource: ColorResource(name: "cherry200", bundle: .module)) }
    static var cherry300: UIColor { UIColor(resource: ColorResource(name: "cherry300", bundle: .module)) }
    static var cherry400: UIColor { UIColor(resource: ColorResource(name: "cherry400", bundle: .module)) }
    static var cherry50: UIColor { UIColor(resource: ColorResource(name: "cherry50", bundle: .module)) }
    static var cherry500: UIColor { UIColor(resource: ColorResource(name: "cherry500", bundle: .module)) }
    static var cherry600: UIColor { UIColor(resource: ColorResource(name: "cherry600", bundle: .module)) }
    static var cherry700: UIColor { UIColor(resource: ColorResource(name: "cherry700", bundle: .module)) }
    static var gray100: UIColor { UIColor(resource: ColorResource(name: "gray100", bundle: .module)) }
    static var gray200: UIColor { UIColor(resource: ColorResource(name: "gray200", bundle: .module)) }
    static var gray300: UIColor { UIColor(resource: ColorResource(name: "gray300", bundle: .module)) }
    static var gray400: UIColor { UIColor(resource: ColorResource(name: "gray400", bundle: .module)) }
    static var gray50: UIColor { UIColor(resource: ColorResource(name: "gray50", bundle: .module)) }
    static var gray500: UIColor { UIColor(resource: ColorResource(name: "gray500", bundle: .module)) }
    static var gray600: UIColor { UIColor(resource: ColorResource(name: "gray600", bundle: .module)) }
    static var gray700: UIColor { UIColor(resource: ColorResource(name: "gray700", bundle: .module)) }
    static var gray800: UIColor { UIColor(resource: ColorResource(name: "gray800", bundle: .module)) }
    static var gray850: UIColor { UIColor(resource: ColorResource(name: "gray850", bundle: .module)) }
    static var gray900: UIColor { UIColor(resource: ColorResource(name: "gray900", bundle: .module)) }
    static var gray950: UIColor { UIColor(resource: ColorResource(name: "gray950", bundle: .module)) }
    static var melon500: UIColor { UIColor(resource: ColorResource(name: "melon500", bundle: .module)) }
    static var melon600: UIColor { UIColor(resource: ColorResource(name: "melon600", bundle: .module)) }
    static var pudding500: UIColor { UIColor(resource: ColorResource(name: "pudding500", bundle: .module)) }
    static var pudding600: UIColor { UIColor(resource: ColorResource(name: "pudding600", bundle: .module)) }
    static var soda500: UIColor { UIColor(resource: ColorResource(name: "soda500", bundle: .module)) }
    static var white25: UIColor { UIColor(resource: ColorResource(name: "white25", bundle: .module)) }
    static var white50: UIColor { UIColor(resource: ColorResource(name: "white50", bundle: .module)) }
    static var white75: UIColor { UIColor(resource: ColorResource(name: "white75", bundle: .module)) }
    static var whiteFixed: UIColor { UIColor(resource: ColorResource(name: "whiteFixed", bundle: .module)) }
}
