// Generated by scripts/gen-assets.sh from Assets.xcassets — DO NOT EDIT.
import SwiftUI
import UIKit

public extension Image {
    static let icCloseRound = Image("Ic_Close_Round", bundle: .module)
    static let imageOnboarding1 = Image("Image-Onboarding-1", bundle: .module)
    static let imageOnboarding2 = Image("Image-Onboarding-2", bundle: .module)
}

public extension UIImage {
    static var icCloseRound: UIImage { UIImage(resource: ImageResource(name: "Ic_Close_Round", bundle: .module)) }
    static var imageOnboarding1: UIImage { UIImage(resource: ImageResource(name: "Image-Onboarding-1", bundle: .module)) }
    static var imageOnboarding2: UIImage { UIImage(resource: ImageResource(name: "Image-Onboarding-2", bundle: .module)) }
}
